### PR TITLE
wireframe set

### PR DESCRIPTION
**Pull request by DilsherB**
1. project basics set with webpack
2. first gray structure is added.
3. some styling added to make page presentable.

### CODE REVIEW

**Comment by tugsem** [comment]
## Invalid Code Review Request ❌ 

Hi @DilsherB  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

🔴 You have submitted a project, that doesn't have:

-  linters 
- readme template

setup
### Here's  a reminder for you to keep in mind when filling out the template:

> README file should be descriptive:
> * All main headers from the [README template](https://github.com/microverseinc/readme-template) should be present  (**if any relevant header is missing, kindly mark the PR as invalid**)
>   * The only **optional** section is FAQ.
>   * Make sure to add the section **Future Features**, including 1-3 potential features to be added.
> * You should **remove the section description**, i.e. "> Describe the tech stack and include only the relevant sections that apply to your project." should be removed and filled in with your custom content.
> * You should remove **template logo**. Optionally, you can replace it with your own logo if you have one.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Zuhaib042 — COMMENTED** [review]
Hi @DilsherB , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have linters files in it.
Kindly consider adding .github/workflows and other linters files in your repo so that Github can assess your linters if they pass or not.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by huseyinbiyik** [comment]
Hi @DilsherB,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Alt Text

## Invalid Code Review Request

You have submitted a project, that has no descriptive Pull Request description. Kindly list the changes you added on this branch like below.
Screenshot 2023-03-07 at 7 59 23 PM



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by DuaneDave — APPROVED** [review]
Hi @DilsherB 👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ PR summary present
✔️ Webpack correctly set up
✔️ Readme is professional and well documented


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
